新增模块
Teahouse-Studios/bot pull request #168
Opened 2022-01-19 15:39 UTC by HornCopper

搓轮子 搓轮子 获取CurseForge模组的下载链接，
绕开了DDoS限制，使用了别人的搜索工具，
但那边仓库已经对接，所以理论上功能相同。

尽可能不要将其和mcmod模块进行整合。

2022-01-20 01:17 UTC, Dianliang233 commented
请先解决一下 Syntax Error 谢谢

2022-01-20 06:07 UTC, HornCopper commented
嗯？不好意思我测试无误后在gh上改了一下
不好意思，这就处理

2022-01-20 06:44 UTC, HornCopper commented
已解决mod_dl.py中可能存在的错误

2022-01-20 12:21 UTC, Dianliang233 commented
请先解决一下 Syntax Error 谢谢

2022-01-20 12:22 UTC, HornCopper commented
不理解 我本地跑起来没问题

2022-01-20 12:22 UTC, HornCopper commented
另：阁下是指__init__.py还是mod_dl.py？
由于环境缺失，恕在下无法使用Console测试__init__.py

2022-01-20 12:23 UTC, Dianliang233 requested changes

2022-01-20 12:23 UTC, Dianliang233 commented on modules/mod_dl/__init__.py
> +    recommend_modules=['mcmod']))
再说一个没问题？

2022-01-20 12:24 UTC, HornCopper commented on modules/mod_dl/__init__.py
> +    recommend_modules=['mcmod']))
哦原来是__init__.py啊（

2022-01-20 12:24 UTC, HornCopper commented on modules/mod_dl/__init__.py
> +    recommend_modules=['mcmod']))
这就改这就改，没Console难受（

2022-01-20 12:25 UTC, Dianliang233 commented
https://www.mcbbs.net/forum.php?mod=redirect&goto=findpost&ptid=1119157&pid=24375906

2022-01-20 12:27 UTC, Dianliang233 commented
> 另：阁下是指__init__.py还是mod_dl.py？ 由于环境缺失，恕在下无法使用Console测试__init__.py

没有环境就装😅我难道还能让一个都无法加载的模块通过 pr 吗

2022-01-20 12:29 UTC, HornCopper commented
怎么 不让人改吗
另外环境缺到还得重新编译Python，会影响到我当前业务。

2022-01-20 12:30 UTC, HornCopper commented
多了个括号，已删除

2022-01-21 11:43 UTC, OasisAkari approved these changes

2022-01-21 11:43 UTC, merged